version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u deven2690 --password 5ddd00e2-77f1-4a65-bc7d-656f8480c1a9
      - IMAGE_REPO_NAME=deven2690/dockerpublish
      - IMAGE_TAG=0.0.1
  build:
    commands:
      - echo Build started on `date` 
      - mvn clean install -Pdocker 
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
artifacts:
  files:
    - 'Dockerfile'
    - 'target/<jar-file-created-as-part-of-the-build>'
